[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
solc="0.8.23"

[rpc_endpoints]
blast-sepolia="${RPC_URl}"

[etherscan]
blast-sepolia = { chain = 168587773, key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
